[package]
name = "eons"
description = "Endless driving experience"
license = "GPL-3.0"
repository = "https://github.com/krissemicolon/eons"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.9.1"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
